name: first_pro
description: "A new Flutter project."
publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: '>=3.8.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  google_fonts: ^6.2.1
  http: ^1.4.0
  cached_network_image: ^3.4.1
  geolocator: ^14.0.2
  url_launcher: ^6.3.2
  cupertino_icons: ^1.0.8
  introduction_screen: ^4.0.0
  shared_preferences: ^2.5.3
  image_picker: ^1.2.0
  flutter_staggered_animations: ^1.1.1
  lottie: ^3.3.1
  animated_text_kit: ^4.2.3
  # flutter_launcher_icons is a dev dependency, moved below
  
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.14.4 # Correctly placed here

flutter:
  uses-material-design: true
  assets:
    - assets/bgl.jpg
    - assets/splash.png
    - assets/shopping cart.json
    - assets/intro_login.png
    - assets/intro_register.png
    - assets/intro_welcome.png
    - assets/Splash.png # Make sure you have this file from before

flutter_native_splash:
  color: "#141A28"
  android: true
  ios: true

# This is for your homescreen icon.
flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/splash.png"
  adaptive_icon_background: "#141A28"
  adaptive_icon_foreground: "assets/Splash.png"